version: '3.8'
services:
  go-server:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/work
    working_dir: /go/src/work
    ports:
      - "2300:2300"
      - "6060:6060"
